import { createHash } from "crypto";
import { prisma } from "./lib/prisma";

function map<T, V>(iter: T[], func: (value: T) => V): V[] {
	return iter.map(func);
}

const a = [1, 2, 3, 4];
const b = map(a, (num) => {
	return num.toString();
});

const els = [
	'\n            <a class="menu-path">Résumé Help<span class="small-icon caret-down"></span></a>\n            <div class="title-bar-dd-content">\n              <ul>\n                <li><a href="/cv-review" itemprop="name">Résumé Review Service</a></li>\n                <li><a href="/cv-writing" itemprop="name">Professional Résumé Writing</a></li>\n                <li><a href="/cv-bundles" itemprop="name">Résumé Bundle Packs</a></li>\n                <li><a href="/cv-templates" itemprop="name">Downloadable Templates</a></li>\n                <li><a href="/cv-help" itemprop="name">View all services</a></li>\n              </ul>\n            </div>\n          ',
	'<a href="/cv-review" itemprop="name">Résumé Review Service</a>',
	'<a href="/cv-writing" itemprop="name">Professional Résumé Writing</a>',
	'<a href="/cv-bundles" itemprop="name">Résumé Bundle Packs</a>',
	'<a href="/cv-templates" itemprop="name">Downloadable Templates</a>',
	'<a href="/cv-help" itemprop="name">View all services</a>',
	'\n            <a itemprop="url" href="https://www.careerhunter.io/?utm_source=careeraddict&amp;utm_medium=topmenu" target="_blank" class="menu-path">Career Test</a>\n          ',
	'\n            <a itemprop="url" href="https://jobs.careeraddict.com/?utm_source=careeraddict&amp;utm_medium=topmenu" target="_blank" class="menu-path">Job Search</a>\n          ',
	'\n            <a itemprop="url" href="/career-paths" class="menu-path">Careers</a>\n          ',
	'\n            <a itemprop="url" href="/advice" class="menu-path">Advice</a>\n          ',
	'\n            <a itemprop="url" href="/videos" class="menu-path">Videos</a>\n          ',
	'\n            <span class="line-seperator"></span>\n          ',
	'\n            <div data-react-class="menu/search" data-react-props="{}" data-react-cache-id="menu/search-0"><div class="search-icon"><div class="magnify"></div></div></div>\n          ',
	'\n           <div data-react-class="menu/userIcon" data-react-props="{}" data-react-cache-id="menu/userIcon-0"></div>\n          ',
	'\n          <div data-toggle="career-advice" class="primary-color drop-down-link browse-categories" id="ddCategoriesToggleBtn">\n            <div class="title-text">Browse Categories</div>\n            <div class="small-icon caret-down"></div>\n          </div>\n        ',
	'\n            <a class="parent-color-on-hover" href="/cvs">CVs &amp; Résumés</a>\n          ',
	'\n            <a class="parent-color-on-hover" href="/interviews">Interviews</a>\n          ',
	'\n            <a class="parent-color-on-hover" href="/job-search">Job Search</a>\n          ',
	'\n            <a class="parent-color-on-hover" href="/choosing-a-career">Choosing a Career</a>\n          ',
	'\n            <a class="parent-color-on-hover" href="/career-development">Career Development</a>\n          ',
	'\n            <a class="parent-color-on-hover" href="/skills">Professional Skills</a>\n          ',
	'\n            <a class="parent-color-on-hover" href="/entrepreneurship">Entrepreneurship</a>\n          ',
	'\n            <a class="parent-color-on-hover" href="/human-resources">HR &amp; Recruitment</a>\n          ',
	'<a>Résumé Help<span class="small-icon caret-down"></span></a><div class="menu-accordion "><a href="/cv-review" class="sub-item">Résumé Review Service</a><a href="/cv-writing" class="sub-item">Professional Résumé Writing</a><a href="/cv-bundles" class="sub-item">Résumé Bundle Packs</a><a href="/cv-templates" class="sub-item">Downloadable Templates</a><a href="/cv-help" class="sub-item">View all services</a></div>',
	'<a href="https://www.careerhunter.io/?utm_source=careeraddict&amp;utm_medium=topmenu" target="_blank">Career Test</a>',
	'<a href="https://jobs.careeraddict.com/?utm_source=careeraddict&amp;utm_medium=topmenu" target="_blank">Job Search</a>',
	'<a href="/career-paths">Careers</a>',
	'<a href="/advice">Advice</a>',
	'<a href="/videos">Videos</a>',
	"<h2><span>Follow Us</span></h2>",
	'<a href="https://www.facebook.com/CareerAddict/" target="_blank"><div class="overlay-icon facebook"></div></a><a href="https://www.youtube.com/CareerAddictVideo" target="_blank"><div class="overlay-icon youtube"></div></a><a href="https://twitter.com/careeraddict" target="_blank"><div class="overlay-icon twitter"></div></a><a href="https://www.linkedin.com/company/career-addict/" target="_blank"><div class="overlay-icon linkedin"></div></a><a href="https://www.instagram.com/careeraddict/" target="_blank"><div class="overlay-icon instagram"></div></a>',
	'\n          <meta itemprop="item" content="https://www.careeraddict.com/cvs">\n          <a href="https://www.careeraddict.com/cvs" class="">\n            <h5 class="category-color" itemprop="name">CVs &amp; Résumés</h5>\n          </a>\n          <meta itemprop="position" content="1">\n        ',
	'\n        <meta itemprop="name" content="200 Hobbies and Interests to Include in Your Résumé">\n        <meta itemprop="item" content="https://www.careeraddict.com/hobbies-cv-list">\n        <meta itemprop="position" content="2">\n          <span class="small-icon published-date"></span>\n          <time datetime="2022-05-19">May 19, 2022</time>\n      ',
	'\n        <span data-react-class="comments/count" data-react-props="{}" data-react-cache-id="comments/count-0" class="comments-area"><span><span class="small-icon comments"></span><span class="comments-number-area"><span class="comments-number">8</span> <span class="hide-for-small-only">Comments</span></span></span></span>\n      ',
	'\n        <span class="small-icon estimation-time"></span>\n        6 min read\n      ',
	'\n                <img alt="Chris Leitch" data-src="//cdn3.careeraddict.com/uploads/avatar/41258/small-chris-leitch.jpg" width="38" height="38" src="//cdn3.careeraddict.com/uploads/avatar/41258/small-chris-leitch.jpg" class="loaded" data-was-processed="true">\n              ',
	'\n            <a href="/author/chris-leitch" class="pad-0" aria-label="Chris Leitch at CareerAddict">\n              <p class="author-name">Chris Leitch</p>\n            </a>\n            <p class="author-label">Editor-in-Chief | Résumé Expert</p>\n          ',
	'<span style="font-size: 20px;"><strong><a href="#should">Should you include them?</a></strong></span>',
	'<span style="font-size: 20px;"><strong><a href="#how">How to choose</a></strong></span>',
	'<span style="font-size: 20px;"><strong><a href="#list">List of 200 hobbies and interests</a></strong></span>',
	'<span style="font-size: 20px;">You’re just starting out in your career and you have limited work and educational experience.</span>',
	'<span style="font-size: 20px;">Your hobbies directly align with the duties listed in the job posting.</span>',
	'<span style="font-size: 20px;">The employer specifically asks about your hobbies in the job posting.</span>',
	'<span style="font-size: 20px;">You have limited skills that directly relate to the job you’re applying for.</span>',
	'<span style="font-size: 20px;">The employer is looking for unique candidates.</span>',
	"are controversial",
	"are potentially dangerous, violent or illegal",
	"reflect antisocial behavior",
	"are listed as a joke that could be misinterpreted",
	"reveal political or religious affiliations",
	'<span style="font-size: 20px;">Animation</span>',
	'<span style="font-size: 20px;"><a href="https://www.careeraddict.com/become-architect">Architecture</a></span>',
	'<span style="font-size: 20px;">Calligraphy</span>',
	'<span style="font-size: 20px;">Candle making</span>',
	'<span style="font-size: 20px;">Cardmaking</span>',
	'<span style="font-size: 20px;">Ceramics</span>',
	'<span style="font-size: 20px;">Crocheting</span>',
	'<span style="font-size: 20px;">Drawing</span>',
	'<span style="font-size: 20px;">Embroidery</span>',
	'<span style="font-size: 20px;"><a href="https://www.careeraddict.com/become-fashion-designer">Fashion design</a></span>',
	'<span style="font-size: 20px;">Filmmaking</span>',
	'<span style="font-size: 20px;">Floristry</span>',
	'<span style="font-size: 20px;">Furniture building</span>',
	'<span style="font-size: 20px;">Gardening</span>',
	'<span style="font-size: 20px;">Glass painting</span>',
	'<span style="font-size: 20px;">Home decorating</span>',
	'<span style="font-size: 20px;">Jewelry making</span>',
	'<span style="font-size: 20px;">Knitting</span>',
	'<span style="font-size: 20px;">Origami</span>',
	'<span style="font-size: 20px;">Painting</span>',
	'<span style="font-size: 20px;"><a href="https://www.careeraddict.com/become-photographer">Photography</a></span>',
	'<span style="font-size: 20px;">Quilling</span>',
	'<span style="font-size: 20px;">Quilting</span>',
	'<span style="font-size: 20px;">Scrapbooking</span>',
	'<span style="font-size: 20px;">Sculpting</span>',
	'<span style="font-size: 20px;">Sewing</span>',
	'<span style="font-size: 20px;">Sketching</span>',
	'<span style="font-size: 20px;">Soap making</span>',
	'<span style="font-size: 20px;">Pottery</span>',
	'<span style="font-size: 20px;">Woodburning</span>',
	'<span style="font-size: 20px;">Woodcarving</span>',
	'<span style="font-size: 20px;">Woodworking</span>',
	'<span style="font-size: 20px;">Action figures</span>',
	'<span style="font-size: 20px;">Amateur geology</span>',
	'<span style="font-size: 20px;">Antiques</span>',
	'<span style="font-size: 20px;">Autographs</span>',
	'<span style="font-size: 20px;">Cars</span>',
	'<span style="font-size: 20px;">Coins</span>',
	'<span style="font-size: 20px;">Comic books</span>',
	'<span style="font-size: 20px;">Dolls</span>',
	'<span style="font-size: 20px;">Fine art</span>',
	'<span style="font-size: 20px;">LEGO sets</span>',
	'<span style="font-size: 20px;">Model diecast cars</span>',
	'<span style="font-size: 20px;">Movie memorabilia</span>',
	'<span style="font-size: 20px;">Music memorabilia</span>',
	'<span style="font-size: 20px;">Sports memorabilia</span>',
	'<span style="font-size: 20px;">Sports trading cards</span>',
	'<span style="font-size: 20px;">Stamps</span>',
	'<span style="font-size: 20px;">Vinyl records</span>',
	'<span style="font-size: 20px;">Watches</span>',
	'<span style="font-size: 20px;">Baking</span>',
	'<span style="font-size: 20px;">Bartending</span>',
	'<span style="font-size: 20px;">Beer tasting</span>',
	'<span style="font-size: 20px;">Brewing</span>',
	'<span style="font-size: 20px;">Coffee roasting</span>',
	'<span style="font-size: 20px;">Cooking</span>',
	'<span style="font-size: 20px;">Grilling</span>',
	'<span style="font-size: 20px;">Mixology</span>',
	'<span style="font-size: 20px;">Sushi making</span>',
	'<span style="font-size: 20px;">Whiskey tasting</span>',
	'<span style="font-size: 20px;">Wine making</span>',
	'<span style="font-size: 20px;">Wine tasting</span>',
	'<span style="font-size: 20px;">3D games</span>',
	'<span style="font-size: 20px;">Arcade games</span>',
	'<span style="font-size: 20px;">Billiards</span>',
	'<span style="font-size: 20px;">Board games</span>',
	'<span style="font-size: 20px;">Bridge</span>',
	'<span style="font-size: 20px;">Card games</span>',
	'<span style="font-size: 20px;">Chess</span>',
	'<span style="font-size: 20px;">Crossword puzzles</span>',
	'<span style="font-size: 20px;">Dominoes</span>',
	'<span style="font-size: 20px;">Geocaching</span>',
	'<span style="font-size: 20px;">Jigsaw puzzles</span>',
	'<span style="font-size: 20px;">Sudoku</span>',
	'<span style="font-size: 20px;">Table tennis</span>',
	'<span style="font-size: 20px;">Video games</span>',
	'<span style="font-size: 20px;">Word scrambles</span>',
	'<span style="font-size: 20px;">App building</span>',
	'<span style="font-size: 20px;"><a href="https://www.careeraddict.com/become-blogger">Blogging</a></span>',
	'<span style="font-size: 20px;">Car restoration</span>',
	'<span style="font-size: 20px;">Model airplanes</span>',
	'<span style="font-size: 20px;">Model cars</span>',
	'<span style="font-size: 20px;">Model railroading</span>',
	'<span style="font-size: 20px;">Model rockets</span>',
	'<span style="font-size: 20px;">Model ships</span>',
	'<span style="font-size: 20px;">Podcasting</span>',
	'<span style="font-size: 20px;">Programming / Coding</span>',
	'<span style="font-size: 20px;">RC boats</span>',
	'<span style="font-size: 20px;">RC cars</span>',
	'<span style="font-size: 20px;">RC helicopters</span>',
	'<span style="font-size: 20px;">RC planes</span>',
	'<span style="font-size: 20px;">Robotics</span>',
	'<span style="font-size: 20px;">Scale miniature building</span>',
	'<span style="font-size: 20px;">Web design</span>',
	'<span style="font-size: 20px;"><a href="https://www.careeraddict.com/successful-youtuber">YouTubing</a></span>',
	'<span style="font-size: 20px;">Choir singing</span>',
	'<span style="font-size: 20px;">Composing music</span>',
	'<span style="font-size: 20px;">DJing</span>',
	'<span style="font-size: 20px;">Mashups</span>',
	'<span style="font-size: 20px;">Opera</span>',
	'<span style="font-size: 20px;">Playing a musical instrument</span>',
	'<span style="font-size: 20px;">Rapping</span>',
	'<span style="font-size: 20px;"><a href="https://www.careeraddict.com/become-singer">Singing</a></span>',
	'<a href="https://www.careeraddict.com/become-actor"><span style="font-size: 20px;">Acting</span></a>',
	'<span style="font-size: 20px;">Ballet</span>',
	'<span style="font-size: 20px;">Breakdancing</span>',
	'<span style="font-size: 20px;">Historical reenactments</span>',
	'<span style="font-size: 20px;">Juggling</span>',
	'<span style="font-size: 20px;">Line dancing</span>',
	'<span style="font-size: 20px;"><a href="https://www.careeraddict.com/real-magic-or-clever-tricks-become-a-magician">Magic tricks</a></span>',
	'<span style="font-size: 20px;">Puppetry</span>',
	'<span style="font-size: 20px;">Salsa</span>',
	'<span style="font-size: 20px;">Standup comedy</span>',
	'<span style="font-size: 20px;">Swing</span>',
	'<span style="font-size: 20px;">Tango</span>',
	'<span style="font-size: 20px;">Waltz</span>',
	'<span style="font-size: 20px;">Animal breeding</span>',
	'<span style="font-size: 20px;">Animal rescue</span>',
	'<span style="font-size: 20px;">Animal training</span>',
	'<span style="font-size: 20px;">Beekeeping</span>',
	'<span style="font-size: 20px;">Dog walking</span>',
	'<span style="font-size: 20px;">Fishkeeping</span>',
	'<span style="font-size: 20px;">Pet fostering</span>',
	'<span style="font-size: 20px;">Pet grooming</span>',
	'<span style="font-size: 20px;">Astrology</span>',
	'<span style="font-size: 20px;">Astronomy</span>',
	'<span style="font-size: 20px;"><a href="https://www.careeraddict.com/become-writer">Freelance writing</a></span>',
	'<span style="font-size: 20px;">Genealogy</span>',
	'<span style="font-size: 20px;">Journaling</span>',
	'<span style="font-size: 20px;"><a href="https://www.careeraddict.com/best-languages">Languages</a></span>',
	'<span style="font-size: 20px;">Meditation</span>',
	'<span style="font-size: 20px;">Neurolinguistic programming</span>',
	'<span style="font-size: 20px;">Novel writing</span>',
	'<span style="font-size: 20px;"><a href="https://www.careeraddict.com/websites-online-courses">Online classes</a></span>',
	'<span style="font-size: 20px;">Play writing</span>',
	'<span style="font-size: 20px;">Poetry</span>',
	'<span style="font-size: 20px;">Reading</span>',
	'<span style="font-size: 20px;">Screenwriting</span>',
	'<span style="font-size: 20px;">Sign language</span>',
	'<span style="font-size: 20px;">Songwriting</span>',
	'<span style="font-size: 20px;">Speed reading</span>',
	'<span style="font-size: 20px;"><a href="https://www.careeraddict.com/volunteering-a-guide-to-increasing-your-employability">Volunteering</a></span>',
	'<span style="font-size: 20px;">Acrobatics</span>',
	'<span style="font-size: 20px;">Archery</span>',
	'<span style="font-size: 20px;">Badminton</span>',
	'<span style="font-size: 20px;">Backpacking travel</span>',
	'<span style="font-size: 20px;">Base jumping</span>',
	'<span style="font-size: 20px;">Baseball</span>',
	'<span style="font-size: 20px;">Basketball</span>',
	'<span style="font-size: 20px;">Birdwatching</span>',
	'<span style="font-size: 20px;">Bodybuilding</span>',
	'<span style="font-size: 20px;">Bowling</span>',
	'<span style="font-size: 20px;">Boxing</span>',
	'<span style="font-size: 20px;">Camping</span>',
	'<span style="font-size: 20px;">Canoeing</span>',
	'<span style="font-size: 20px;">Croquet</span>',
	'<span style="font-size: 20px;">Cycling</span>',
	'<span style="font-size: 20px;">Darts</span>',
	'<span style="font-size: 20px;">Diving</span>',
	'<span style="font-size: 20px;">Fantasy football</span>',
	'<span style="font-size: 20px;">Fencing</span>',
	'<span style="font-size: 20px;">Figure skating</span>',
	'<span style="font-size: 20px;">Fishing</span>',
	'<span style="font-size: 20px;">Flying</span>',
	'<span style="font-size: 20px;">Football</span>',
	'<span style="font-size: 20px;">Go karting</span>',
	'<span style="font-size: 20px;">Golf</span>',
	'<span style="font-size: 20px;">Gymnastics</span>',
	'<span style="font-size: 20px;">Hang gliding</span>',
	'<span style="font-size: 20px;">Hiking</span>',
	'<span style="font-size: 20px;">Horse racing</span>',
	'<span style="font-size: 20px;">Horseback riding</span>',
	'<span style="font-size: 20px;">Ice skating</span>',
	'<span style="font-size: 20px;">Kayaking</span>',
	'<span style="font-size: 20px;">Marathon running</span>',
	'<span style="font-size: 20px;">Martial arts</span>',
	'<span style="font-size: 20px;">Mountain biking</span>',
	'<span style="font-size: 20px;">Mountaineering</span>',
	'<span style="font-size: 20px;">Paintball</span>',
	'<span style="font-size: 20px;">Paragliding</span>',
	'<span style="font-size: 20px;">Pilates</span>',
	'<span style="font-size: 20px;">Rock climbing</span>',
	'<span style="font-size: 20px;">Running</span>',
	'<span style="font-size: 20px;">RV traveling</span>',
	'<span style="font-size: 20px;">Sailing</span>',
	'<span style="font-size: 20px;">Scuba diving</span>',
	'<span style="font-size: 20px;">Sightseeing</span>',
	'<span style="font-size: 20px;">Skateboarding</span>',
	'<span style="font-size: 20px;">Skiing</span>',
	'<span style="font-size: 20px;">Skydiving</span>',
	'<span style="font-size: 20px;">Snowboarding</span>',
	'<span style="font-size: 20px;">Squash</span>',
	'<span style="font-size: 20px;">Surfing</span>',
	'<span style="font-size: 20px;">Swimming</span>',
	'<span style="font-size: 20px;">Tennis</span>',
	'<span style="font-size: 20px;"><a href="https://www.careeraddict.com/travel-jobs">Travel</a></span>',
	'<span style="font-size: 20px;">Water skiing</span>',
	'<span style="font-size: 20px;">Weight training</span>',
	'<span style="font-size: 20px;">Windsurfing</span>',
	'<span style="font-size: 20px;">Yoga</span>',
	'<span style="font-size: 20px;">Only list hobbies and interests if it makes sense to do so (they’re directly relevant to the job you’re applying for, for example) <em>and</em> you have space for them.</span>',
	'<span style="font-size: 20px;">Research the company, and tailor your hobbies and interests around their culture.</span>',
	'<span style="font-size: 20px;">Choose hobbies and interests that demonstrate your transferable skills and unique personality traits.</span>',
	'<span style="font-size: 20px;">Stay away from controversial hobbies or potentially illegal activities (such as gambling, pole dancing, hunting and hacking) or interests relating to your political or religious affiliations.</span>',
	"Add a dedicated section for them at the end of your résumé.",
	"List them as separate bullet points and, ideally, briefly expand on each one in up to one sentence.",
	"Don’t list more than five hobbies and interests.",
	'<strong><a href="https://www.careeraddict.com/cv-hobbies-write"><span style="font-size: 20px;">How to Write about Hobbies on Your Résumé</span></a></strong>',
	'<strong><span style="font-size: 20px;"><a href="https://www.careeraddict.com/include-structure-cv">How to Structure Your Résumé</a></span></strong>',
	'<strong><span style="font-size: 20px;"><a href="https://www.careeraddict.com/answer-what-do-you-do-in-your-spare-time">How to Answer “What Do You Do in Your Spare Time?”</a></span></strong>',
	"<p>Topics:</p>",
	'\n            <p>\n              <a class="topic" href="/topics/hobbies-and-interests">Hobbies and Interests</a>\n            </p>\n          ',
	'\n            <p>\n              <a class="topic" href="/topics/resume-sections">Résumé Sections</a>\n            </p>\n          ',
];

const main = async () => {
	// const response = await fetch(
	// 	"https://www.careeraddict.com/hobbies-cv-list"
	// );
	// const data = await response.text();
	// els.forEach((el, i) => {
	// 	if (el.includes("li")) console.log(i, el);
	// });
	// await prisma.chat.create({
	// 	data: {
	// 		Name: "cool chat",
	// 	},
	// });
};

main();
