const cheerio = require("cheerio");

const main = async () => {
	const response = await fetch(
		"https://www.careeraddict.com/hobbies-cv-list"
	);
	const html = await response.text();
	const $ = cheerio.load(html);
	let stuff = [];
	$('<span style="font-size: 20px;"></span>', html).each(function () {
		// if ($(this)) stuff.push($(this).text());
		console.log(`"${$(this).text()}",`);
	});
	// console.log(stuff);
};

main();

const interests = [
	"Animation",
	"Architecture",
	"Calligraphy",
	"Candle making",
	"Cardmaking",
	"Ceramics",
	"Crocheting",
	"Drawing",
	"Embroidery",
	"Fashion design",
	"Filmmaking",
	"Floristry",
	"Furniture building",
	"Gardening",
	"Glass painting",
	"Home decorating",
	"Jewelry making",
	"Knitting",
	"Origami",
	"Painting",
	"Photography",
	"Quilling",
	"Quilting",
	"Scrapbooking",
	"Sculpting",
	"Sewing",
	"Sketching",
	"Soap making",
	"Pottery",
	"Woodburning",
	"Woodcarving",
	"Woodworking",
	"Action figures",
	"Amateur geology",
	"Antiques",
	"Autographs",
	"Cars",
	"Coins",
	"Comic books",
	"Dolls",
	"Fine art",
	"LEGO sets",
	"Model diecast cars",
	"Movie memorabilia",
	"Music memorabilia",
	"Sports memorabilia",
	"Sports trading cards",
	"Stamps",
	"Vinyl records",
	"Watches",
	"Baking",
	"Bartending",
	"Beer tasting",
	"Brewing",
	"Coffee roasting",
	"Cooking",
	"Grilling",
	"Mixology",
	"Sushi making",
	"Whiskey tasting",
	"Wine making",
	"Wine tasting",
	"3D games",
	"Arcade games",
	"Billiards",
	"Board games",
	"Bridge",
	"Card games",
	"Chess",
	"Crossword puzzles",
	"Dominoes",
	"Geocaching",
	"Jigsaw puzzles",
	"Sudoku",
	"Table tennis",
	"Video games",
	"Word scrambles",
	"App building",
	"Blogging",
	"Car restoration",
	"Model airplanes",
	"Model cars",
	"Model railroading",
	"Model rockets",
	"Model ships",
	"Podcasting",
	"Programming / Coding",
	"RC boats",
	"RC cars",
	"RC helicopters",
	"RC planes",
	"Robotics",
	"Scale miniature building",
	"Web design",
	"YouTubing",
	"Choir singing",
	"Composing music",
	"DJing",
	"Mashups",
	"Opera",
	"Playing a musical instrument",
	"Rapping",
	"Singing",
	"Acting",
	"Ballet",
	"Breakdancing",
	"Historical reenactments",
	"Juggling",
	"Line dancing",
	"Magic tricks",
	"Puppetry",
	"Salsa",
	"Standup comedy",
	"Swing",
	"Tango",
	"Waltz",
	"Animal breeding",
	"Animal rescue",
	"Animal training",
	"Beekeeping",
	"Dog walking",
	"Fishkeeping",
	"Pet fostering",
	"Pet grooming",
	"Astrology",
	"Astronomy",
	"Freelance writing",
	"Genealogy",
	"Journaling",
	"Languages",
	"Meditation",
	"Neurolinguistic programming",
	"Novel writing",
	"Online classes",
	"Play writing",
	"Poetry",
	"Reading",
	"Screenwriting",
	"Sign language",
	"Songwriting",
	"Speed reading",
	"Volunteering",
	"Acrobatics",
	"Archery",
	"Badminton",
	"Backpacking travel",
	"Base jumping",
	"Baseball",
	"Basketball",
	"Birdwatching",
	"Bodybuilding",
	"Bowling",
	"Boxing",
	"Camping",
	"Canoeing",
	"Croquet",
	"Cycling",
	"Darts",
	"Diving",
	"Fantasy football",
	"Fencing",
	"Figure skating",
	"Fishing",
	"Flying",
	"Football",
	"Go karting",
	"Golf",
	"Gymnastics",
	"Hang gliding",
	"Hiking",
	"Horse racing",
	"Horseback riding",
	"Ice skating",
	"Kayaking",
	"Marathon running",
	"Martial arts",
	"Mountain biking",
	"Mountaineering",
	"Paintball",
	"Paragliding",
	"Pilates",
	"Rock climbing",
	"Running",
	"RV traveling",
	"Sailing",
	"Scuba diving",
	"Sightseeing",
	"Skateboarding",
	"Skiing",
	"Skydiving",
	"Snowboarding",
	"Squash",
	"Surfing",
	"Swimming",
	"Tennis",
	"Travel",
	"Water skiing",
	"Weight training",
	"Windsurfing",
	"Yoga",
];
