import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  const interests = [
    "Agriculture",
    "Animal science",
    "Business",
    "Cosmetology",
    "Customer service",
    "Creative",
    "Education",
    "Engineering",
    "Finance",
    "Healthcare",
    "Hospitality",
    "Human Resources",
    "Information Technology",
    "Leadership",
    "Marketing",
    "Operations",
    "Sales",
    "Forester",
    "Biochemist",
    "Food scientist",
    "Animal geneticist",
    "Crop geneticist",
    "Farmer",
    "Wildlife biologist",
    "Horticulturalist",
    "Plant nursery attendant",
    "Plant biologist",
    "Wildlife inspector",
    "Soil and plant scientist",
    "Beekeeper",
    "Aquatic ecologist",
    "Conservationist",
    "Veterinarian",
    "Zoologist",
    "Groomer",
    "Animal control officer",
    "Kennel attendant",
    "Pet walker",
    "Animal sitter",
    "Animal shelter manager",
    "Veterinary assistant",
    "Animal nutritionist",
    "Biologist",
    "Wildlife rehabilitator",
    "Breeder",
    "Veterinary pathologist",
    "Veterinary ophthalmologist",
    "Project manager",
    "Sales manager",
    "Actuary",
    "Business teacher",
    "Business reporter",
    "Admissions representative",
    "Office manager",
    "Office clerk",
    "Assistant buyer",
    "Business development manager",
    "Salon manager",
    "Makeup artist",
    "Nail technician",
    "Message therapist",
    "Barber",
    "Beautician",
    "Skincare specialist",
    "Fashion designer",
    "Esthetician",
    "Electrologist",
    "Cosmetology instructor",
    "Hairdresser",
    "Fashion show stylist",
    "Spa manager",
    "Wedding stylist",
    "Call centre agent",
    "Client services coordinator",
    "Technical support representative",
    "Virtual assistant",
    "Customer care associate",
    "Retail sales associate",
    "Cashier",
    "Concierge",
    "Customer service manager",
    "Help desk assistant",
    "Account coordinator",
    "Service advisor",
    "Bank teller",
    "Front desk coordinator",
    "Client services manager",
    "Art director",
    "Graphic designer",
    "Writer",
    "Editor",
    "Illustrator",
    "Public relations specialist",
    "Actor",
    "Singer",
    "Producer",
    "Web developer",
    "Architect",
    "Multimedia animator",
    "Painter",
    "Tattoo artist",
    "Dancer",
    "Floral designer",
    "English teacher",
    "University lecturer",
    "Tutor",
    "Test scorer",
    "Test administrator",
    "Assistant professor",
    "Headteacher",
    "Superintendent",
    "Deputy headteacher",
    "Substitute teacher",
    "Librarian",
    "Math teacher",
    "Science teacher",
    "Instructional designer",
    "Guidance counsellor",
    "Civil engineer",
    "Mechanical engineer",
    "Chemical engineer",
    "Biological engineer",
    "Nuclear engineer",
    "Aerospace engineer",
    "Electrical engineer",
    "Environmental engineer",
    "Geological engineer",
    "Marine engineer",
    "Oil and gas engineer",
    "Safety engineer",
    "Product engineer",
    "Compliance engineer",
    "Senior process engineer﻿",
    "Financial planner",
    "Financial advisor",
    "Budget analyst",
    "Credit analyst",
    "Financial services representative",
    "Financial manager",
    "Cost estimator",
    "Loan officer",
    "Investment banking analyst",
    "Financial auditor",
    "Nurse",
    "Doctor",
    "Carer",
    "Physical therapist",
    "Personal trainer",
    "Pharmacist",
    "Pharmacy assistant",
    "Dental hygienist",
    "Orthodontist",
    "Dental assistant",
    "Occupational therapy aide",
    "Dentist",
    "Surgical assistant",
    "Dietitian",
    "Travel agent",
    "Housekeeper",
    "Porter",
    "Casino pit boss",
    "Hotel clerk",
    "Meeting planner",
    "Executive chef",
    "Tour guide",
    "Flight attendant",
    "Event manager",
    "Human resources manager",
    "Compensation and benefits manager",
    "Administrative assistant",
    "Human resources generalist",
    "Talent acquisition coordinator",
    "Executive recruiter",
    "Human resources specialist",
    "Human resources director",
    "Human resources assistant",
    "Labour relations specialist",
    "Human resources consultant",
    "International human resources associate",
    "Human resources systems administrator",
    "Compensation advisor",
    "Training and development manager",
    "UX designer",
    "UI developer",
    "IT manager",
    "Computer programmer",
    "SQL developer",
    "Software developer",
    "Web administrator",
    "Data architect",
    "Business intelligence developer",
    "Mobile application developer",
    "Information security analyst",
    "Front-end web developer",
    "Java developer",
    "Database manager",
    "Software engineer",
    "Chief of operations",
    "Team leader",
    "Manager",
    "Executive",
    "Director",
    "Supervisor",
    "Principal",
    "President",
    "Vice President",
    "Team lead",
    "Marketing coordinator",
    "Marketing manager",
    "Marketing assistant",
    "Marketing director",
    "Product marketing manager",
    "Creative director",
    "Demand generation director",
    "Social media manager",
    "Account manager",
    "Brand manager",
    "Content marketing manager",
    "Marketing analyst",
    "Marketing consultant",
    "Social media coordinator",
    "Search engine optimization specialist",
    "Chief operations officer",
    "Logistics coordinator",
    "Warehouse supervisor",
    "Supply chain specialist",
    "Distribution supervisor",
    "Supply chain coordinator",
    "Operations assistant",
    "Continuous improvement lead",
    "Operations manager",
    "Sales representative",
    "Sales director",
    "Sales manager",
    "Insurance sales agent",
    "Telemarketer",
    "Retail salesperson",
    "Store manager",
    "Account executive",
    "B2B sales specialist",
    "Sales analyst",
    "Real estate broker",
    "Sales associate",
    "Sales consultant",
    "Collection agent",
    "Regional sales manager",
  ];

  await prisma.user.deleteMany();
  console.log("DELETED ALL USERS.")

  Promise.all(
    interests.map((interestName) =>
      prisma.interest.upsert({
        where: {
          name: interestName,
        },
        update: {},
        create: {
          name: interestName,
        },
      })
    )
  ).then((values) => {
    console.log(values);
  });


}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
